import type { Metadata } from "next";
import "../global.css";
import { Inter } from "next/font/google";

import "@radix-ui/themes/styles.css";
import ReactQueryProvider from "../providers/ReactQueryProvider";
import ThemeProvider from "@/providers/ThemeProvider";
import { UserContextProvider } from "@/hooks/user";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>
          <ThemeProvider
            appearance="light"
            accentColor="tomato"
            grayColor="gray"
            panelBackground="solid"
          >
            <UserContextProvider>{children}</UserContextProvider>
          </ThemeProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
